[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps =
    adafruit/Adafruit MLX90640@^1.1.2
    adafruit/Adafruit BusIO
    adafruit/Adafruit NeoPixel@^1.12.0
lib_ignore = Audio - Adafruit Fork, SdFat - Adafruit Fork, Adafruit TinyUSB Library
build_flags =
    -mfpu=fpv5-d16
    -mfloat-abi=hard
    -DAUDIO_SAMPLE_RATE_EXACT=160000.0f
