[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

monitor_speed = 115200
lib_ldf_mode = chain+

lib_deps =
    adafruit/Adafruit MLX90640@^1.1.2
    adafruit/Adafruit BusIO
    adafruit/Adafruit NeoPixel@^1.12.0

lib_ignore = Audio - Adafruit Fork, SdFat - Adafruit Fork, Adafruit TinyUSB Library

build_flags =
    -D USB_SERIAL
    -D AUDIO_SAMPLE_RATE_EXACT=72000.0f
    -mfpu=fpv5-d16
    -mfloat-abi=hard
